
export const raw_data = [
    {
      reg_no: "BU/TEC/2024/STM2/01",
      sname: "Anushka",
      afiliation: "Bundelkhand University, Jhansi",
      assessment1:22,
      assessment2:18,
      ideation:10,
      pds:9.6,
      total:59.6,
      percentage:'59.60%',
      grade:'B',
    },{
      reg_no: "BU/TEC/2024/STM2/02",
      sname: "ASHOK S J",
      afiliation: "Sri Ramakrishna College of Arts & Science, Coimbatore, Tamil Nadu",
      assessment1:37,
      assessment2:36,
      ideation:10,
      pds:10,
      total:93,
      percentage:'93.00%',
      grade:'O',
    },{
      reg_no: "BU/TEC/2024/STM2/03",
      sname: "Asmita singh",
      afiliation: "Bundelkhand University jhansi ",
      assessment1:24,
      assessment2:26,
      ideation:10,
      pds:5.2,
      total:65.2,
      percentage:'65.20%',
      grade:'B+',
    },{
      reg_no: "BU/TEC/2024/STM2/04",
      sname: "Atharva Tiwari",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:34,
      assessment2:30,
      ideation:10,
      pds:7.9,
      total:81.9,
      percentage:'81.90%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/05",
      sname: "Ayush Raj",
      afiliation: "Bundelkhand University, Jhansi ",
      assessment1:31,
      assessment2:24,
      ideation:9,
      pds:9.6,
      total:73.6,
      percentage:'73.60%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/06",
      sname: "Chandra Prakash Patel",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:33,
      assessment2:26,
      ideation:10,
      pds:10,
      total:79,
      percentage:'79.00%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/07",
      sname: "Kanchi Khandelwal",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:28,
      assessment2:32,
      ideation:10,
      pds:8.3,
      total:78.3,
      percentage:'78.30%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/08",
      sname: "Mageswari.G",
      afiliation: "Sri Ramakrishna College of arts & Science, Tamilnadu",
      assessment1:29,
      assessment2:20,
      ideation:10,
      pds:10,
      total:69,
      percentage:'69.00%',
      grade:'B+',
    },{
      reg_no: "BU/TEC/2024/STM2/09",
      sname: "Mridhul kattal",
      afiliation: "Bundelkhand University jhansi",
      assessment1:35,
      assessment2:36,
      ideation:10,
      pds:6.3,
      total:87.3,
      percentage:'87.30%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/10",
      sname: "Omika pal",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:27,
      assessment2:32,
      ideation:10,
      pds:9.2,
      total:78.2,
      percentage:'78.20%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/11",
      sname: "Pragya sengar",
      afiliation: "Bundelkhand university",
      assessment1:30,
      assessment2:32,
      ideation:3,
      pds:7.3,
      total:72.3,
      percentage:'72.30%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/12",
      sname: "Saksham Gupta",
      afiliation: "Bundelkhand University, Jhansi ",
      assessment1:31,
      assessment2:30,
      ideation:9,
      pds:9.4,
      total:79.4,
      percentage:'79.40%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/13",
      sname: "Samriddhi Bisaria",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:27,
      assessment2:30,
      ideation:8,
      pds:9.4,
      total:74.4,
      percentage:'74.40%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/14",
      sname: "Sania Zaidi",
      afiliation: "Bipin Bihari Degree College , Jhansi",
      assessment1:34,
      assessment2:38,
      ideation:5,
      pds:5.8,
      total:82.8,
      percentage:'82.80%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/15",
      sname: "Sanju Singh",
      afiliation: "Bundelkhand University Jhansi ",
      assessment1:26,
      assessment2:22,
      ideation:6,
      pds:9.2,
      total:63.2,
      percentage:'63.20%',
      grade:'B+',
    },{
      reg_no: "BU/TEC/2024/STM2/16",
      sname: "SHAMBHAVI SHANDILYA",
      afiliation: "Bundelkhand university jhansi ",
      assessment1:30,
      assessment2:30,
      ideation:10,
      pds:7.7,
      total:77.7,
      percentage:'77.70%',
      grade:'A',
    },{
      reg_no: "BU/TEC/2024/STM2/17",
      sname: "Sneha kumari",
      afiliation: "Bundelkhand University ",
      assessment1:33,
      assessment2:30,
      ideation:10,
      pds:9.2,
      total:82.2,
      percentage:'82.20%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/18",
      sname: "SNEHA.M",
      afiliation: "Sri Ramakrishna College of Arts & Science, Nava India,  Coimbatore , Tamilnadu",
      assessment1:35,
      assessment2:32,
      ideation:10,
      pds:10,
      total:87,
      percentage:'87.00%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/19",
      sname: "Sonam kushwaha",
      afiliation: "Bundelkhand university jhansi (U.P.) ",
      assessment1:13,
      assessment2:18,
      ideation:10,
      pds:9,
      total:50,
      percentage:'50.00%',
      grade:'B',
    },{
      reg_no: "BU/TEC/2024/STM2/20",
      sname: "Subhavarshini.R",
      afiliation: "Sri Ramakrishna College of arts and science, Tamil Nadu",
      assessment1:31,
      assessment2:30,
      ideation:10,
      pds:10,
      total:81,
      percentage:'81.00%',
      grade:'A+',
    },{
      reg_no: "BU/TEC/2024/STM2/21",
      sname: "Yash Sharma",
      afiliation: "Bundelkhand University, Jhansi",
      assessment1:33,
      assessment2:32,
      ideation:10,
      pds:7.7,
      total:82.7,
      percentage:'82.70%',
      grade:'A+',
    }

   
  ];